Repository CSID-DGU/2024-1-OSSProj-ComfyRide-01, pull requests merged in 2024-06, with the labels that each got.

#68 Update README.md & Minor changes in Doc/
  Doc/2_1_OSSProj_01_버스태워조_중간보고서.md
  Doc/2_2_OSSProj_01_버스태워조_중간발표자료.pdf
  Doc/4_2_OSSProj_01_버스태워조_회의록.md
  Doc/4_3_OSSProj_01_버스태워조_제품구성배포운영자료.md
  Doc/4_4_OSSProj_01_버스태워조_Overivew.md
  README.md
Labels: documentation

#74 최종보고서 초안 작성
  .gitattributes
  Doc/3_1_OSSProj_01_버스태워조_최종보고서.md
  local_image.jpg
Labels: documentation

#82 Document 수정
  Doc/4_3_OSSProj_01_버스태워조_제품구성배포운영자료.md
  README.md
Labels: documentation

#86 Udate UI and Bug fix
  Src/lib/screen/Cart_Screen.dart
  Src/lib/screen/Login_Screen.dart
  Src/lib/screen/Style_Recommendation.dart
  Src/lib/screen/choice_style.dart
  Src/lib/screen/explain_FTTI.dart
  Src/lib/screen/main_screen.dart
  Src/lib/screen/splash_screen.dart
  Src/lib/screen/today_recommendation.dart
Labels: bug, enhancement

#87 제품 구성 배포 운영자료 수정, flow chart 업로드
  Doc/3_1_OSSProj_01_버스태워조_최종보고서.md
  Doc/4_3_OSSProj_01_버스태워조_제품구성배포운영자료.md
  Doc/imgs/flow_chart.png
  Doc/imgs/최종보고서_img/3.FTTI설명.png
  Doc/imgs/최종보고서_img/4-1.추천스타일조회.png
  Doc/imgs/최종보고서_img/4-2.추천스타일찜.png
  Doc/imgs/최종보고서_img/4-3.찜목록.png
  Doc/imgs/최종보고서_img/4-4.쇼핑몰 이동화면.png
  Doc/imgs/최종보고서_img/5-2.쇼핑몰 이동화면.png
Labels: documentation

#89 Update logout UI
  Src/lib/screen/choice_style.dart
  Src/lib/screen/main_screen.dart
Labels: enhancement

#93 Doc 수정
  Doc/3_1_OSSProj_01_버스태워조_최종보고서.md
  Doc/4_1_OSSProj_01_버스태워조_범위_일정_이슈관리.md
  Doc/4_4_OSSProj_01_버스태워조_Overivew.md
  Doc/imgs/최종보고서_img/Effect.png
  Doc/imgs/최종보고서_img/이슈_FTTI정의.png
  Doc/imgs/최종보고서_img/이슈_무한로딩.png
  Doc/imgs/최종보고서_img/이슈_신규유저페이지.png
  README.md
Labels: documentation

#95 Copyright 추가, RTUpload.py 수정
  Src/MLModel/RTUpload.py
  Src/MLModel/mlModel.py
  Src/MLModel/testing.ipynb
Labels: documentation

#98 mlModel 작동하도록 수정
  Src/MLModel/mlModel.py
Labels: bug
